[package]
name = "tatami_achievements"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
repository.workspace = true

[tool]
fmt.workspace = true

[dependencies]
starknet.workspace = true
dojo.workspace = true
tatami_world = { path = "../world" }
achievement = { git = "https://github.com/cartridge-gg/arcade", tag = "v0.0.0" }

[lib]
